"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("Servizis", [
      {
        masterId: 2,
        title: "Ногти",
        description: "Маникюр и аккуратный уход за ногтями",
        price: 10000.0,
        duration: 60.0,
        categoryId: 1,
        isActive: true,
        image: "/услуги на главной/ногти9.jpg",
      },
      {
        masterId: 13,
        title: "Массаж",
        description: "Расслабляющий массаж для лица и тела",
        price: 5000.0,
        duration: 90.0,
        categoryId: 4,
        isActive: true,
        image: "/услуги на главной/массаж8.jpg",
      },
      {
        masterId: 11,
        title: "Волосы",
        description: "Укладка и образ для любого события",
        price: 3000.0,
        duration: 60.0,
        categoryId: 3,
        isActive: true,
        image: "/услуги на главной/прическа2.jpg",
      },
      {
        masterId: 8,
        title: "Косметология",
        description: "Уход за кожей лица и свежий тон",
        price: 4000.0,
        duration: 60.0,
        categoryId: 2,
        isActive: true,
        image: "/услуги на главной/косметология11.jpg",
      },
      {
        masterId: 10,
        title: "Макияж",
        description: "Легкий и выразительный макияж под образ",
        price: 3500.0,
        duration: 60.0,
        categoryId: 5,
        isActive: true,
        image: "/услуги на главной/макияж1.jpg",
      },
      {
        masterId: 11,
        title: "Укладка",
        description: "Профессиональная укладка волос",
        price: 2500.0,
        duration: 60.0,
        categoryId: 3,
        isActive: true,
        image: "/услуги на главной/укладка3.jpg",
      },
      {
        masterId: 7,
        title: "Педикюр",
        description: "Уход за ногами и ногтями",
        price: 1500.0,
        duration: 60.0,
        categoryId: 1,
        isActive: true,
        image: "/услуги на главной/педикюр4.jpg",
      },
      {
        masterId: 9,
        title: "Эпиляция",
        description: "Классическая эпиляция бикини и депиляция",
        price: 2000.0,
        duration: 60.0,
        categoryId: 2,
        isActive: true,
        image: "/услуги на главной/эпиляция5.jpg",
      },
      {
        masterId: 13,
        title: "Массаж лица",
        description: "Расслабляющий массаж для лица и шеи",
        price: 3000.0,
        duration: 60.0,
        categoryId: 4,
        isActive: true,
        image: "/услуги на главной/массаж лица6.jpg",
      },
      {
        masterId: 13,
        title: "Массаж тела",
        description: "Расслабляющий массаж для всего тела",
        price: 5000.0,
        duration: 90.0,
        categoryId: 4,
        isActive: true,
        image: "/услуги на главной/массаж тела7.jpg",
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Servizis", null, {});
  },
};
